# Generated by Django 2.2.4 on 2019-11-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191101_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reference_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
